schema: "1"
id: conditionalStage
variables:
- name: regions
  description: Regions to deploy
  type: list
  defaultValue: ['us-west-1', 'eu-west-1']
- name: forcePush
  description: Override execution windows
  defaultValue: false

stages:
- id: bake
  type: bake
  config:
    # Bake stage configuration 

- id: judgement-uswest1
  type: manualJudgement
  dependsOn: 
  - bake
  when:
  - "{{contains regions 'us-west-1'}}"
  config:
    # Manual judgement stage configuration 

- id: deploy-uswest1
  type: deploy
  dependsOn: 
  - judgement-uswest1
  when:
  - "{{contains regions 'us-west-1'}}"
  config:
    # Deploy stage configuration 

- id: deploy-euwest1
  type: deploy
  dependsOn: 
  - bake
  when:
  - "{{contains regions 'eu-west-1'}}"
  config:
    # Deploy stage configuration 
